version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=worldrates
      - POSTGRES_PASSWORD=worldrates
  worldrates:
    image: ib/worldrates
    working_dir: /opt/worldrates
    volumes:
      - ./config:/opt/worldrates/config
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    entrypoint: "java -jar ./bin/worldrates.jar --spring.config.location=./config/application.properties"
    healthcheck:
      test: "curl http://worldrates:8080/rates?page=0&size=1"
      interval: 10s
      timeout: 10s
      retries: 3
