version: '3'
services:
  postgres:
    image: postgres:12.2
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=worldrates
      - POSTGRES_PASSWORD=worldrates
