quarkus:
  datasource:
    url: "jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGUSER:worldrates}"
    username: ${PGUSER:worldrates}
    password: ${PGPASSWORD:worldrates}
    driver: org.postgresql.Driver
  flyway:
    migrate-at-start: true

app:
  sync:
    cron: "0 0 1 * * ?"
  providers:
    bnr:
      enabled: true
      url: 'https://www.bnr.ro/nbrfxrates.xml'
    ecb:
      enabled: true
      url: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip'
    era:
      enabled: true
      url: 'https://api.exchangerate-api.com/v4/latest/EUR'


