spring:
  datasource:
    url: "jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGUSER:worldrates}"
    username: ${PGUSER:worldrates}
    password: ${PGPASSWORD:worldrates}
  jpa:
    open-in-view: false

app:
  sync:
    cron: '0 1 0 * * *'
  providers:
    bnr:
      enabled: true
      url: 'https://www.bnr.ro/nbrfxrates.xml'
    ecb:
      enabled: true
      url: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip'

management:
  endpoints:
    enabled-by-default: true
  server:
    port: 8081


