apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: 'world-rates.apps.us-west-1.starter.openshift-online.com'
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: worldrates-frontend-cluster-ip-service
              servicePort: 8080
          - path: /api/(.*)
            backend:
              serviceName: worldrates-cluster-ip-service
              servicePort: 8080
