apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldrates-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: worldrates
  template:
    metadata:
      labels:
        component: worldrates
    spec:
      containers:
        - image: ibaranga/worldrates
          name: worldrates
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pguser
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres

