quarkus:
  datasource:
    url: "jdbc:postgresql://postgres:5432/worldrates"
    username: worldrates
    password: worldrates
    driver: org.postgresql.Driver
  flyway:
    migrate-at-start: true

app:
  sync:
    cron: "0 0 1 * * ?"
  providers:
    bnr:
      enabled: true
      url: 'https://www.bnr.ro/nbrfxrates.xml'
    ecb:
      enabled: true
      url: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip'
    era:
      enabled: true
      url: 'https://api.exchangerate-api.com/v4/latest/EUR'
