version: '3'
services:
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=worldrates
      - POSTGRES_PASSWORD=worldrates
  worldrates:
    build:
      dockerfile: Dockerfile
      context: ../
    working_dir: /opt/worldrates
    volumes:
      - ./config:/opt/worldrates/config
    depends_on:
      - postgres
    healthcheck:
      test: "curl http://worldrates:8080/rates?page=0&size=1"
      timeout: 10s
      retries: 3
  integrationtest:
    depends_on:
      - worldrates
    build:
      context: ../
      dockerfile: Dockerfile.it
    entrypoint: "mvn -Dtest=none -DfailIfNoTests=false -Dit.baseUrl=http://worldrates:8080 verify -Pit"


