name: OpenShift Deploy
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v1.1
      with:
        version: 'latest'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.OPENSHIFT_SERVER_URL }}", "acceptUntrustedCerts": "true"}'
        cmd: |          
          'oc apply -f k8s'
