name: Run integration tests
on:
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run integration tests
        run: 'cd integration; docker-compose up --build --abort-on-container-exit'
